"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import SideBar from "./components/siderbar/sidebar";
import OperatorSideBar from "./components/operatorsidebar/sidebar";
import Auth from "./components/auth/auth";
import { useEffect, useState } from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  

  const [authenticated,setAuthenticated] = useState(localStorage.getItem("userdata"));

  //  useEffect(()=>{
  //   (function (){
      
    
  //     if(authenticated){
  //     setAuthenticated(true)
  //     }
  //     else{
  //       setAuthenticated(false)
  //     }
  //   })()
  //  })
  return (

    <>
    {authenticated ?


    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin = "true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;1,400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
      <div className="m-0 p-0 flex h-[100vh] overflow-hidden">
          <div className="m-0 w-[18%] h-[100%]">
            <SideBar/>  
          </div>
          <div className="w-[82%] h-[100%]">
            <Navbar/>
            <div className="border-solid border-t-4 border-l-4 h-[100%] py-5 px-2 bg-[#F3F3F3]">{ children }</div>
          </div>
        </div>
      </body>
    </html>
          :  <html lang="en">
          <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin = "true" />
            <link
              href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;1,400&display=swap"
              rel="stylesheet"
            />
          </head>
          <body className={inter.className}>
          <div className="m-0 p-0 ">
              
              
              <Auth setAuth={setAuthenticated}/>
            </div>
          </body>
        </html>}

    </>
  );
}
